### ISSUE TITLE
I have a  problem in week01 homework. "Making it better (orthogonal Procrustean problem)"

### ISSUE THREAD

**Issue by Andy1314Chen** [yandexdataschool/nlp_course#28]
```python
from numpy import linalg as la
def learn_transform(X_train, Y_train):
    """ 
    :returns: W* : float matrix[emb_dim x emb_dim] as defined in formulae above
    """
    u, sigma, vt = la.svd(np.matmul(X_train.T, Y_train)) # 300*300
    W = np.matmul(u,vt.T)
    return W
```
I complete the SVD code, but the result is bad.

```python
W = learn_transform(X_train, Y_train)
ru_emb.most_similar([np.matmul(uk_emb["серпень"], W)])

[('Раззаков', 0.2569316625595093),
 ('Tyrrell', 0.25682011246681213),
 ('Cosworth', 0.2490822821855545),
 ('ANZ', 0.24802428483963013),
 ('owned', 0.24786119163036346),
 ('Bowie', 0.24696007370948792),
 ('Хемингуэй', 0.24553290009498596),
 ('debut', 0.24303579330444336),
 ('Тэдзука', 0.24089395999908447),
 ('underground', 0.24075618386268616)]
```
I don't know why.

**Comment by Tinyrat** [comment]
兄弟你发错地方了吧 490302867 邮箱490302867@qq.com 签名由 网易邮箱大师 定制 On 03/12/2019 10:52, 陈自强 wrote: from numpy import linalg as la

def learn_transform(X_train, Y_train):

    """ 

    :returns: W* : float matrix[emb_dim x emb_dim] as defined in formulae above

    """

    u, sigma, vt = la.svd(np.matmul(X_train.T, Y_train)) # 300*300

    W = np.matmul(u,vt.T)

    return W I complete the SVD code, but the result is bad. W = learn_transform(X_train, Y_train)

ru_emb.most_similar([np.matmul(uk_emb["серпень"], W)])



[('Раззаков', 0.2569316625595093),

 ('Tyrrell', 0.25682011246681213),

 ('Cosworth', 0.2490822821855545),

 ('ANZ', 0.24802428483963013),

 ('owned', 0.24786119163036346),

 ('Bowie', 0.24696007370948792),

 ('Хемингуэй', 0.24553290009498596),

 ('debut', 0.24303579330444336),

 ('Тэдзука', 0.24089395999908447),

 ('underground', 0.24075618386268616)] I don't know why. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Andy1314Chen** [comment]
老哥，应该发在哪里啊？没看到有交流的地方，待会儿会删的。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Tinyrat <notifications@github.com>
发送时间: Tuesday, March 12, 2019 10:57:09 AM
收件人: yandexdataschool/nlp_course
抄送: 陈自强; Author
主题: Re: [yandexdataschool/nlp_course] I have a problem in week01 homework. "Making it better (orthogonal Procrustean problem)" (#28)

兄弟你发错地方了吧 490302867 邮箱490302867@qq.com 签名由 网易邮箱大师 定制 On 03/12/2019 10:52, 陈自强 wrote: from numpy import linalg as la
def learn_transform(X_train, Y_train):
"""
:returns: W* : float matrix[emb_dim x emb_dim] as defined in formulae above
"""
u, sigma, vt = la.svd(np.matmul(X_train.T, Y_train)) # 300*300
W = np.matmul(u,vt.T)
return W I complete the SVD code, but the result is bad. W = learn_transform(X_train, Y_train)
ru_emb.most_similar([np.matmul(uk_emb["серпень"], W)])

[('Раззаков', 0.2569316625595093),
('Tyrrell', 0.25682011246681213),
('Cosworth', 0.2490822821855545),
('ANZ', 0.24802428483963013),
('owned', 0.24786119163036346),
('Bowie', 0.24696007370948792),
('Хемингуэй', 0.24553290009498596),
('debut', 0.24303579330444336),
('Тэдзука', 0.24089395999908447),
('underground', 0.24075618386268616)] I don't know why. ― You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

―
