### ISSUE TITLE
can't download the data

### ISSUE THREAD

**Issue by Winona1234** [yandexdataschool/nlp_course#72]
hi, i can't acquire download the data in the code when i run the code,such as this code:
# download the data:
!wget https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1 -O ./quora.txt
# alternative download link: https://yadi.sk/i/BPQrUu1NaTduEw
the outcome is:/bin/bash: wget: command not found

**Comment by Yaziwel** [comment]
So did I :(

**Comment by justheuristic** [comment]
Hi! The issue is probably because you don't have wget installed

On Mac OS (and linux distros with curl), try this:
`!curl -L https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1 > ./quora.txt`

If it doesn't work, just
- open https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1 in your browser
- save as quora.txt __in the same folder as the notebook__


If neither of them works, please attach the error screenshots here

**Comment by aooxin** [comment]
May be you  can use wsl in windows, or use browser.
